# Generated by Django 4.1.5 on 2023-01-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Shop title')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Item title')),
                ('description', models.TextField(max_length=200, verbose_name='Item description')),
                ('price', models.PositiveIntegerField(verbose_name='Item price')),
                ('shop', models.ManyToManyField(to='app_market.shop')),
            ],
        ),
    ]
