# Generated by Django 4.1.5 on 2023-01-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0002_remove_item_shop_shop_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ManyToManyField(to='app_market.shop'),
        ),
    ]
