# Generated by Django 4.1.5 on 2023-01-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0005_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amt',
            field=models.PositiveIntegerField(default=1, verbose_name='Item amount'),
        ),
    ]
