# Generated by Django 4.1.5 on 2023-01-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0009_item_sell_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
