# Generated by Django 4.1.5 on 2023-01-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0010_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
