# Generated by Django 4.1.5 on 2023-01-29 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_market', '0013_remove_history_user_history_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='profile',
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
